version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./.env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb:/data/db
    networks:
      db-api-net:
        ipv4_address: 192.168.112.2
    ports:
      - "27017:27017"

  api:
    build:
      context: api
    container_name: waterapi
    env_file:
      - ./.env
    environment:
      PORT: 8899
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

    depends_on:
      - db
    volumes:
      - ./api/src:/api:rw
      - ./api/images:/images:rw
    restart: "no"
    networks:
      db-api-net:
        ipv4_address: 192.168.112.3
    ports:
      - "8899:80"

volumes:
  mongodb:

networks:
  db-api-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.112.0/24
          gateway: 192.168.112.1